#!/bin/bash

switch="$1"
user=$(whoami)

EXTERNAL_MON=HDMI-1-1
INTERNAL_MON=eDP-1-1

case "$switch" in
  enable|-e)
    xrandr --output $EXTERNAL_MON --left-of $INTERNAL_MON --auto
    /home/${user}/.fehbg
    pkill dunst
    ;;
  disable|-d)
    xrandr --output $EXTERNAL_MON --off
    /home/${user}/.fehbg
    pkill dunst
    ;;
  *)
    echo "Invalid option. Exiting."
    ;;
esac
